API Assignment- 2
anushreeSonak/APIAutomation pull request #3
Opened 2023-05-05 12:54 UTC by anushreeSonak

2023-05-08 06:44 UTC, prashantkawa requested changes

2023-05-08 06:44 UTC, prashantkawa commented on APIAssignment/pom.xml
remove extra spaces

2023-05-08 06:44 UTC, prashantkawa commented on APIAssignment/src/test/java/APIAssignments/ProductLists.java
> +import java.util.logging.Logger;
Use Logger from apache.Log4j library

2023-05-08 06:44 UTC, prashantkawa commented on APIAssignment/src/test/java/APIAssignments/ProductLists.java
> +    private static Logger logger = Logger.getLogger("ProductLists.class");
Declare logger as final

2023-05-08 06:59 UTC, anushreeSonak commented on APIAssignment/pom.xml
done !!

2023-05-08 07:00 UTC, anushreeSonak commented on APIAssignment/src/test/java/APIAssignments/ProductLists.java
> +import java.util.logging.Logger;
done !!

2023-05-08 07:00 UTC, anushreeSonak commented on APIAssignment/src/test/java/APIAssignments/ProductLists.java
> +    private static Logger logger = Logger.getLogger("ProductLists.class");
done !!

2023-05-09 04:33 UTC, prashantkawa approved these changes
Approving PR

2023-05-09 09:36 UTC, amitsahu8 approved these changes

2023-05-09 10:57 UTC, merged