API Assignment -4
anushreeSonak/APIAutomation pull request #5
Opened 2023-05-10 07:20 UTC by anushreeSonak

2023-05-10 07:27 UTC, prashantkawa requested changes

2023-05-10 07:27 UTC, prashantkawa commented on APIAssignment/src/test/java/APIAssignments/PutBrand.java
> +    private static Logger logger = Logger.getLogger("PutBrandList.class");
Use final here

2023-05-10 07:27 UTC, prashantkawa commented on APIAssignment/src/test/java/APIAssignments/PutBrand.java
> +
remove extra spaces

2023-05-10 07:27 UTC, prashantkawa commented on APIAssignment/src/test/java/APIAssignments/PutBrand.java
> +
same here

2023-05-10 07:27 UTC, prashantkawa commented on APIAssignment/src/test/java/APIAssignments/PutBrand.java
> +import java.io.IOException;
Add readme file for problem statement and output

2023-05-10 11:26 UTC, prashantkawa requested changes

2023-05-10 11:26 UTC, prashantkawa commented on APIAssignment/src/test/java/APIAssignments/PutBrand.java
> +import java.util.logging.Logger;
use Logger from apache.log4j library

2023-05-10 12:10 UTC, prashantkawa approved these changes
Approving PR

2023-05-11 08:01 UTC, vrushalee123 approved these changes

2023-05-11 08:01 UTC, merged